require("funni.plugins-setup")
require("funni.plugins.nvim-cmp")
require("funni.core.options")
require("funni.core.keymaps")
require("funni.core.colorscheme")
require("funni.plugins.comment")
require("funni.plugins.nvim-tree")
require("funni.plugins.lualine")
require("funni.plugins.telescope")
require("funni.plugins.lsp.mason")
require("funni.plugins.lsp.lspconfig")
require("funni.plugins.lsp.null-ls")
require("funni.plugins.autopairs")
require("funni.plugins.treesitter")
require("funni.plugins.gitsigns")

vim.opt.clipboard:prepend({ "unnamed", "unnamedplus" })
